# Install micromamba with:
#   "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
# micromamba env create -f environment.yaml

name: fiftyone-train

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.8.15
  # - hydra-core=1.3.2
  - opencv=4.4.0
  - ffmpeg=4.3
  - clearml

  - pytorch::pytorch=2.3.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision=0.18.1


  - pip>=23
  - pip:
    - fiftyone=0.24.1
    - ultralytics=8.2.32
    
